Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"

    config.vm.provider "virtualbox" do |v, override|
        v.memory = 2024
        v.cpus = 4
        v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
        v.customize ["modifyvm", :id, "--vram", "12"]
        v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    end

  end
