[tool.poetry]
name = "devpy"
version = "0.1.0"
description = ""
authors = ["Aleksei Shtepa <a@shtepa.net>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
