---
  - name: Print os facts
    hosts: all
    # remote_user: micard
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}{{ host_info }}"
