version: '3.2'
services:
  elastic:
    image: docker.io/alekseishtepa/elastic:7.17.4
    build: .
    container_name: elastic-7
    environment:
      - discovery.type=single-node
      - node.name=netology_test
  #  - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 9200:9200
    volumes:
      - "_data:/var/lib/elastic-7"
      - "_logs:/var/log/elastic-7"
      - "_snapshots:/usr/share/elasticsearch/snapshots"
    networks:
      - elastic

networks:
  elastic:

# volumes:
#   db-data: