---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: "yc-network-ssd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.size }}
...