all:
  hosts:
    node1:
      ansible_host: 130.193.54.37
      ansible_user: centos
    node2:
      ansible_host: 130.193.53.144
      ansible_user: centos
    node3:
      ansible_host: 130.193.54.135
      ansible_user: centos
    node4:
      ansible_host: 130.193.52.109
      ansible_user: centos
    node5:
      ansible_host: 130.193.55.176
      ansible_user: centos
    node6:
      ansible_host: 51.250.28.65
      ansible_user: centos
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
