---
- name: Install Clickhouse
  tags: clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
  post_tasks:
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  tags: vector
  hosts: vector
  become: true
  vars:
    config_clickhouse_host: hostvars['clickhouse-01']['ansible_host']
    vecrot_version: "0.23.0"
  roles:
    - vector_role


- name: Install Lighthouse
  tags: lighthouse
  hosts: app
  roles:
    - lighthouse_role
